# Notebook 1: Einführung und Daten

**Statistik für Data Science** · Kurs 3,906 · Bachelor Computer Science · HS2026
Universität St. Gallen

---
### Projektteam:
- Andrin Greitmann
- Noah Appenzeller
- Manuel Schmid

---

Dieses Notebook führt die Inhalte von **VL01 (Einführung & Daten)** in Python aus.

## 0. Setup
Importiert `pandas`, `numpy`, `seaborn` und `matplotlib` und setzt den Seed.

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Seed: Startwert für den Zufallsgenerator. Gleicher Seed bei jedem Durchlauf damit Resultate deterministisch & reproduzierbar sind. 
# Den Wert selbst haben wir beliebig gewählt, wir haben ihn als erstes vor der Analyse gewählt und danach nicht mehr geändert.
# Der Seed wird für alles Zufällige in allen Notebooks verwendet.
SEED = 2001
RNG = np.random.default_rng(SEED)

# Plot-Defauls
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (7.5, 4.2)
plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.titlesize"] = 13
plt.rcParams["axes.labelsize"] = 11

In [3]:
import sys

print("Python  ", sys.version.split()[0])
for modul in (np, pd, sns):
    print(f"{modul.__name__:8s}", modul.__version__)
print("Seed    ", SEED)

Python   3.14.4
numpy    2.5.3
pandas   3.0.6
seaborn  0.13.2
Seed     2001

### Unseren Datensatz laden

In [4]:
from ucimlrepo import fetch_ucirepo

# Datensatz direkt aus dem UCI Repository laden (ID 117 = Census-Income KDD)
census_income_kdd = fetch_ucirepo(id=117)

# Etwas spezielles an unserem Datenset: ucimlrepo liefert die Daten aufgeteilt in Features und Target. 
# (Wahrscheinlich für Machine Learning Projekte/Algorithmen)
# Target ist das Einkommen (über/unter 50K), Features sind alle anderen Merkmale.
X = census_income_kdd.data.features
y = census_income_kdd.data.targets

# Für die EDA wollten wir alle Spalten in einem DataFrame damit das Einkommen mit den anderen Merkmalen verglichen werden kann.
# join() funktioniert hier zum Glück recht einfach, weil X und y dieselben Zeilen in derselben Reihenfolge haben.
census = X.join(y)

# Metadaten: Herkunft, Beschreibung und Erhebung des Datensatzes (Damit wir auf Bias analysieren können)
print("Metadata: " + str(census_income_kdd.metadata))

print(f"Rows: {census.shape[0]}, Columns: {census.shape[1]}")

# Variablenbeschreibung: Name, Typ und Bedeutung jeder Spalte (Grundlage um später Messniveau zu bestimmen)
print("Variable descriptions:")

display(census_income_kdd.variables)

Metadata: {'uci_id': 117, 'name': 'Census-Income (KDD)', 'repository_url': 'https://archive.ics.uci.edu/dataset/117/census+income+kdd', 'data_url': 'https://archive.ics.uci.edu/static/public/117/data.csv', 'abstract': 'This data set contains weighted census data extracted from the 1994 and 1995 current population surveys conducted by the U.S. Census Bureau.', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 299285, 'num_features': 41, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Education Level', 'Marital Status', 'Race', 'Sex', 'Other', 'Nationality', 'Income'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2000, 'last_updated': 'Fri Mar 08 2024', 'dataset_doi': '10.24432/C5N30T', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "This data set contains weighted census data extracted from the 1994 and 1995 Current Population Surveys conducted by the U.S. Census Bureau. The data contains 41 demographic and employment related variables. \r\n\r\nThe instance weight indicates the number of people in the population that each record represents due to stratified sampling. To do real analysis and derive conclusions, this field must be used. This attribute should *not* be used in the classifiers. \r\n\r\nOne instance per line with comma delimited fields. There are 199523 instances in the data file and 99762 in the test file. \r\n\r\nThe data was split into train/test in approximately 2/3, 1/3 proportions using MineSet's MIndUtil mineset-to-mlc. \r\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'More information detailing the meaning of the attributes can be found in the Census Bureau\'s documentation To make use of the data descriptions at this site, the following mappings to the Census Bureau\'s internal database column names will be needed: \r\n\r\nage\t\t\t\t\t\tAAGE\r\nclass of worker\t\t\t\t\tACLSWKR\r\nindustry code\t\t\t\t\tADTIND\r\noccupation code\t\t\t\t\tADTOCC\r\nadjusted gross income\t\t\t\tAGI\r\neducation\t\t\t\t\tAHGA\r\nwage per hour\t\t\t\t\tAHRSPAY\r\nenrolled in edu inst last wk\t\t\tAHSCOL\r\nmarital status\t\t\t\t\tAMARITL\r\nmajor industry code\t\t\t\tAMJIND\r\nmajor occupation code\t\t\t\tAMJOCC\r\nmace\t\t\t\t\t\tARACE\r\nhispanic Origin\t\t\t\t\tAREORGN\r\nsex\t\t\t\t\t\tASEX\r\nmember of a labor union\t\t\t\tAUNMEM\r\nreason for unemployment\t\t\t\tAUNTYPE\r\nfull or part time employment stat\t\tAWKSTAT\r\ncapital gains\t\t\t\t\tCAPGAIN\r\ncapital losses\t\t\t\t\tCAPLOSS\r\ndivdends from stocks\t\t\t\tDIVVAL\r\nfederal income tax liability\t\t\tFEDTAX\r\ntax filer status\t\t\t\tFILESTAT\r\nregion of previous residence\t\t\tGRINREG\r\nstate of previous residence\t\t\tGRINST\r\ndetailed household and family stat\t\tHHDFMX\r\ndetailed household summary in household\t\tHHDREL\r\ninstance weight\t\t\t\t\tMARSUPWT\r\nmigration code-change in msa\t\t\tMIGMTR1\r\nmigration code-change in reg\t\t\tMIGMTR3\r\nmigration code-move within reg\t\t\tMIGMTR4\r\nlive in this house 1 year ago\t\t\tMIGSAME\r\nmigration prev res in sunbelt\t\t\tMIGSUN\r\nnum persons worked for employer\t\t\tNOEMP\r\nfamily members under 18\t\t\t\tPARENT\r\ntotal person earnings\t\t\t\tPEARNVAL\r\ncountry of birth father\t\t\t\tPEFNTVTY\r\ncountry of birth mother\t\t\t\tPEMNTVTY\r\ncountry of birth self\t\t\t\tPENATVTY\r\ncitizenship\t\t\t\t\tPRCITSHP\r\ntotal person income\t\t\t\tPTOTVAL\r\nown business or self employed\t\t\tSEOTR\r\ntaxable income amount\t\t\t\tTAXINC\r\nfill inc questionnaire for veteran\'s admin\tVETQVA\r\nveterans benefits\t\t\t\tVETYN\r\nweeks worked in year\t\t\t\tWKSWORK\r\n\r\nNote that Incomes have been binned at the $50K level to present a binary classification problem, much like the original UCI/ADULT database. The goal field of this data, however, was drawn from the "total person income" field rather than the "adjusted gross income" and may, therefore, behave differently than the orginal ADULT goal field. \r\n', 'citation': None}}
Rows: 199523, Columns: 42
Variable descriptions:

,name,role,type,demographic,description,units,missing_values
0,AAGE,Feature,Integer,Age,age,None,no
1,ACLSWKR,Feature,Categorical,NaN,class of worker,None,no
2,ADTINK,Feature,Integer,NaN,industry code,None,no
3,ADTOCC,Feature,Integer,Occupation,occupation code,None,no
4,AHGA,Feature,Integer,Education Level,education,None,no
5,AHSCOL,Feature,Categorical,Education Level,enrolled in edu last week,None,no
6,AMARITL,Feature,Categorical,Marital Status,marital status,None,no
7,AMJIND,Feature,Categorical,NaN,major industry code,None,no
8,AMJOCC,Feature,Categorical,Occupation,major occupation code,None,no
9,ARACE,Feature,Categorical,Race,race,None,no
10,AREORGN,Feature,Categorical,NaN,hispanic origin,None,no
11,ASEX,Feature,Categorical,Sex,sex,None,no
12,AUNMEM,Feature,Categorical,NaN,member of a labor union,None,no
13,AUNTYPE,Feature,Categorical,NaN,reason for unemployment,None,no
14,AWKSTAT,Feature,Integer,NaN,full or part time employment stat,None,no
15,CAPGAIN,Feature,Integer,NaN,capital gains,None,no
16,GAPLOSS,Feature,Integer,NaN,capital losses,None,no
17,DIVVAL,Feature,Categorical,NaN,dividends from stocks,None,no
18,FILESTAT,Feature,Categorical,NaN,tax filer status,None,no
19,GRINREG,Feature,Categorical,NaN,region of previous residence,None,no
20,GRINST,Feature,Categorical,NaN,state of previous residence,None,no
21,HHDFMX,Feature,Continuous,Other,detailed household and family stat,None,no
22,HHDREL,Feature,Categorical,NaN,detailed household summary in household,None,no
23,MARSUPWRT,Feature,Categorical,NaN,instance weight,None,no
24,MIGMTR1,Feature,Categorical,NaN,migration code-change in msa,None,yes
25,MIGMTR3,Feature,Categorical,NaN,migration code-change in reg,None,yes
26,MIGMTR4,Feature,Categorical,NaN,migration code-move within reg,None,yes
27,MIGSAME,Feature,Integer,NaN,live in this house 1 year ago,None,no
28,MIGSUN,Feature,Categorical,NaN,migration prev res in sunbelt,None,yes
29,NOEMP,Feature,Categorical,NaN,num persons worked for employer,None,no
30,PARENT,Feature,Categorical,NaN,family members under 18,None,no
31,PEFNTVTY,Feature,Categorical,NaN,country of birth father,None,yes
32,PEMNTVTY,Feature,Integer,NaN,country of birth mother,None,yes
33,PENATVTY,Feature,Categorical,Nationality,country of birth self,None,no
34,PRCITSHP,Feature,Integer,NaN,citizenship,None,no
35,SEOTR,Feature,Integer,NaN,own business or self employed,None,no
36,VETQVA,Feature,Categorical,NaN,fill inc questionaire for veteran's admin,None,no
37,VETYN,Feature,Categorical,NaN,veterans benefits,None,no
38,WKSWORK,Feature,Categorical,NaN,weeks worked in year,None,no
39,income,Target,Binary,Income,below or above $50k,None,no
40,AHRSPAY,Feature,Integer,NaN,wage per hour,None,no
41,year,Feature,Integer,NaN,94 or 95,None,no

## 1. Datentypen und Messniveaus
Erster Blick auf unseren Datensatz:

In [5]:
census.info()

<class 'pandas.DataFrame'>
RangeIndex: 199523 entries, 0 to 199522
Data columns (total 42 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   AAGE       199523 non-null  int64
 1   ACLSWKR    199523 non-null  str
 2   ADTINK     199523 non-null  int64
 3   ADTOCC     199523 non-null  int64
 4   AHGA       199523 non-null  str
 5   AHSCOL     199523 non-null  str
 6   AMARITL    199523 non-null  str
 7   AMJIND     199523 non-null  str
 8   AMJOCC     199523 non-null  str
 9   ARACE      199523 non-null  str
 10  AREORGN    199523 non-null  str
 11  ASEX       199523 non-null  str
 12  AUNMEM     199523 non-null  str
 13  AUNTYPE    199523 non-null  str
 14  AWKSTAT    199523 non-null  str
 15  CAPGAIN    199523 non-null  int64
 16  GAPLOSS    199523 non-null  int64
 17  DIVVAL     199523 non-null  int64
 18  FILESTAT   199523 non-null  str
 19  GRINREG    199523 non-null  str
 20  GRINST     198815 non-null  str
 21  HHDFMX     199523 non-null  str
 22  HHDREL     199523 non-null  str
 23  MARSUPWRT  199523 non-null  float64
 24  MIGMTR1    99827 non-null   str
 25  MIGMTR3    99827 non-null   str
 26  MIGMTR4    99827 non-null   str
 27  MIGSAME    199523 non-null  str
 28  MIGSUN     99827 non-null   str
 29  NOEMP      199523 non-null  int64
 30  PARENT     199523 non-null  str
 31  PEFNTVTY   192810 non-null  str
 32  PEMNTVTY   193404 non-null  str
 33  PENATVTY   196130 non-null  str
 34  PRCITSHP   199523 non-null  str
 35  SEOTR      199523 non-null  int64
 36  VETQVA     199523 non-null  str
 37  VETYN      199523 non-null  int64
 38  WKSWORK    199523 non-null  int64
 39  AHRSPAY    199523 non-null  int64
 40  year       199523 non-null  int64
 41  income     199523 non-null  str
dtypes: float64(1), int64(12), str(29)
memory usage: 63.9 MB

### Wichtigste Erkenntnisse zur Datenqualität und Vollständigkeit

1. **Nicht jede Spalte ist vollständig:**
Ein signifikanter Teil des Datensatzes weist Lücken auf. Wir haben hier drei Spalten als Beispiele herausgesucht:
    - **`MIGMTR1`** (Migration Code - Change in MSA) hat nur 99'827 von 199'523 Einträgen (es fehlen knapp 50 % der Daten).
    - **`PEFNTVTY`** (Country of Birth Father) hat 192'810 von 199'523 Einträgen (es fehlen 6.713 Werte).
    - **`GRINST`** (State of Previous Residence) hat 198'815 von 199'523 Einträgen (es fehlen 708 Werte).

2. **Systematische Lücken bei migrationsspezifischen Daten:**
Auffällig ist, dass die Spalten `MIGMTR1`, `MIGMTR3`, `MIGMTR4` und `MIGSUN` alle exakt dieselbe Anzahl an nicht-leeren Werten (99'827) aufweisen. Dies deutet stark darauf hin, dass diese Werte nicht zufällig fehlen sondern aufgrund einer gemeinsamen Abhängigkeit. 

3. **Fehlerhafte Metadaten-Dokumentation (`missing_values` Spalte):**
Ein Problem erkannten wir bei der Dokumentationsspalte `missing_values`. Dort wird bei einigen Spalten fälschlicherweise der Wert `no` angegeben, obwohl `df.info()` eindeutig Lücken belegt. Zum Beispiel die Spalte `PENATVTY`, bei der 3'393 Werte fehlen. Man darf sich bei der Vorverarbeitung also nicht blind auf die textuelle Dokumentation verlassen.

4. **Der `dtype` ist nicht das Messniveau:** Zum Beispiel ist `ADTOCC` als `int64` typisiert, aber es handelt sich um eine nominale Skala (Kategoriencodes für Berufe ohne jegliche Rangfolge). Hier würde Pandas zwar einen Mittelwert berechnen, dies wäre mathematisch aber nicht zulässig, da es keinen „durchschnittlichen Beruf“ gibt.

In [8]:
def spalten_ueberblick(df: pd.DataFrame, beispiele: int = 3) -> pd.DataFrame:
    """Kompakter Steckbrief je Spalte: dtype, Anzahl eindeutiger Werte, fehlende Werte, Beispiele.

    Erster Schritt bei jedem unbekannten Datensatz.
    """
    zeilen = []
    for spalte in df.columns:
        s = df[spalte]
        werte = s.dropna().unique()[:beispiele]
        zeilen.append(
            {
                "dtype": str(s.dtype),
                "eindeutig": s.nunique(dropna=True),
                "fehlend": int(s.isna().sum()),
                "fehlend_%": round(s.isna().mean() * 100, 1),
                "beispiele": ", ".join(map(str, werte)),
            }
        )
    return pd.DataFrame(zeilen, index=df.columns)


spalten_ueberblick(census)

,dtype,eindeutig,fehlend,fehlend_%,beispiele
AAGE,int64,91,0,0.0,"73, 58, 18"
ACLSWKR,str,9,0,0.0,"Not in universe, Self-employed-not incorpora..."
ADTINK,int64,52,0,0.0,"0, 4, 40"
ADTOCC,int64,47,0,0.0,"0, 34, 10"
AHGA,str,17,0,0.0,"High school graduate, Some college but no de..."
AHSCOL,str,3,0,0.0,"Not in universe, High school, College or un..."
AMARITL,str,7,0,0.0,"Widowed, Divorced, Never married"
AMJIND,str,24,0,0.0,"Not in universe or children, Construction, ..."
AMJOCC,str,15,0,0.0,"Not in universe, Precision production craft ..."
ARACE,str,5,0,0.0,"White, Asian or Pacific Islander, Amer Indi..."
AREORGN,str,10,0,0.0,"All other, Do not know, Central or South Am..."
ASEX,str,2,0,0.0,"Female, Male"
AUNMEM,str,3,0,0.0,"Not in universe, No, Yes"
AUNTYPE,str,6,0,0.0,"Not in universe, Job loser - on layoff, Oth..."
AWKSTAT,str,8,0,0.0,"Not in labor force, Children or Armed Forces..."
CAPGAIN,int64,132,0,0.0,"0, 5178, 991"
GAPLOSS,int64,113,0,0.0,"0, 1590, 1977"
DIVVAL,int64,1478,0,0.0,"0, 6000, 100"
FILESTAT,str,6,0,0.0,"Nonfiler, Head of household, Joint both und..."
GRINREG,str,6,0,0.0,"Not in universe, South, Northeast"
GRINST,str,50,708,0.4,"Not in universe, Arkansas, Utah"
HHDFMX,str,38,0,0.0,"Other Rel 18+ ever marr not in subfamily, Ho..."
HHDREL,str,8,0,0.0,"Other relative of householder, Householder, ..."
MARSUPWRT,float64,99800,0,0.0,"1700.09, 1053.55, 991.95"
MIGMTR1,str,9,99696,50.0,"MSA to MSA, Nonmover, NonMSA to nonMSA"
MIGMTR3,str,8,99696,50.0,"Same county, Nonmover, Different region"
MIGMTR4,str,9,99696,50.0,"Same county, Nonmover, Different state in S..."
MIGSAME,str,3,0,0.0,"Not in universe under 1 year old, No, Yes"
MIGSUN,str,3,99696,50.0,"Yes, Not in universe, No"
NOEMP,int64,7,0,0.0,"0, 1, 6"
PARENT,str,5,0,0.0,"Not in universe, Both parents present, Moth..."
PEFNTVTY,str,42,6713,3.4,"United-States, Vietnam, Philippines"
PEMNTVTY,str,42,6119,3.1,"United-States, Vietnam, Columbia"
PENATVTY,str,42,3393,1.7,"United-States, Vietnam, Columbia"
PRCITSHP,str,5,0,0.0,"Native- Born in the United States, Foreign b..."
SEOTR,int64,3,0,0.0,"0, 2, 1"
VETQVA,str,3,0,0.0,"Not in universe, No, Yes"
VETYN,int64,3,0,0.0,"2, 0, 1"
WKSWORK,int64,53,0,0.0,"0, 52, 30"
AHRSPAY,int64,1240,0,0.0,"0, 1200, 876"
year,int64,2,0,0.0,"95, 94"
income,str,2,0,0.0,"-50000, 50000+."

### Die vier Messniveaus

| Skala | Eigenschaft | Erlaubte Statistik |
|---|---|---|
| **Nominal** | Kategorien ohne Ordnung | Modus, Häufigkeiten |
| **Ordinal** | Rangfolge, Abstände undefiniert | zusätzlich Median, Perzentile |
| **Intervall** | gleiche Abstände, kein natürlicher Nullpunkt | zusätzlich Mittelwert, Standardabweichung |
| **Ratio** | absoluter Nullpunkt | zusätzlich Verhältnisse, geometrisches Mittel |

In [10]:
# Inhaltliche Zuordnung. Sie steht bewusst als Hand-Mapping da, weil sie sich
# nicht aus dem dtype ableiten laesst.
MESSNIVEAU = {
    "AAGE": "ratio",          # 0 Jahre ist ein echter Nullpunkt
    "ACLSWKR": "nominal",     # Arbeiterklasse (z.B. Private, Federal Gov)
    "ADTINK": "nominal",      # Industrie-Code, int64 aber reiner Code ohne Rang
    "ADTOCC": "nominal",      # Berufs-Code, int64 aber reiner Code ohne Rang
    "AHGA": "ordinal",        # Bildungsabschluss (hat eine logische Rangfolge)
    "AHSCOL": "nominal",      # Einschreibung Schule/Uni
    "AMARITL": "nominal",     # Familienstand
    "AMJIND": "nominal",      # Hauptbranche
    "AMJOCC": "nominal",      # Hauptberufsgruppe
    "ARACE": "nominal",       # Ethnie/Rasse
    "AREORGN": "nominal",     # Hispanische Herkunft
    "ASEX": "nominal",        # Geschlecht
    "AUNMEM": "nominal",      # Gewerkschaftsmitgliedschaft
    "AUNTYPE": "nominal",     # Grund für Arbeitslosigkeit
    "AWKSTAT": "nominal",     # Vollzeit-/Teilzeit-Status
    "CAPGAIN": "ratio",       # Kapitalgewinne (0 $ ist ein echter Nullpunkt)
    "GAPLOSS": "ratio",       # Kapitalverluste (0 $ ist ein echter Nullpunkt)
    "DIVVAL": "ratio",        # Dividenden aus Aktien (0 $ ist ein echter Nullpunkt)
    "FILESTAT": "nominal",    # Steuerstatus
    "GRINREG": "nominal",     # Region des vorherigen Wohnsitzes
    "GRINST": "nominal",      # Bundesstaat des vorherigen Wohnsitzes
    "HHDFMX": "nominal",      # Detaillierte Haushaltsstruktur
    "HHDREL": "nominal",      # Beziehung im Haushalt
    "MARSUPWRT": "ratio",     # Gewichtung / Instance Weight
    "MIGMTR1": "nominal",     # Migrationscode (MSA)
    "MIGMTR3": "nominal",     # Migrationscode (Region)
    "MIGMTR4": "nominal",     # Migrationscode (innerhalb Region)
    "MIGSAME": "nominal",     # Gleiches Haus wie vor 1 Jahr (Ja/Nein-Code)
    "MIGSUN": "nominal",      # Migration (Sunbelt)
    "NOEMP": "ratio",         # Anzahl der Beschäftigten beim Arbeitgeber
    "PARENT": "nominal",      # Elternpräsenz im Haushalt
    "PEFNTVTY": "nominal",    # Geburtsland Vater
    "PEMNTVTY": "nominal",    # Geburtsland Mutter
    "PENATVTY": "nominal",    # Geburtsland Selbst
    "PRCITSHP": "nominal",    # Staatsbürgerschaft
    "SEOTR": "nominal",       # Selbstständigkeit (Code)
    "VETQVA": "nominal",      # Fragebogen für Veteranen
    "VETYN": "nominal",       # Veteranenstatus (Ja/Nein)
    "WKSWORK": "ratio",       # Gearbeitete Wochen im Jahr (0 ist echter Nullpunkt)
    "AHRSPAY": "ratio",       # Stundenlohn (0 $ ist echter Nullpunkt)
    "year": "intervall",      # Jahreszahlen haben keinen natürlichen Nullpunkt
    "income": "ordinal",      # Einkommensklasse (z.B. <50k, >=50k), hat Rangfolge
}

zuordnung = pd.DataFrame(
    {
        "dtype": census.dtypes.astype(str),
        "messniveau": pd.Series(MESSNIVEAU),
    }
)
zuordnung["mittelwert_zulaessig"] = zuordnung["messniveau"].isin(["intervall", "ratio"])
zuordnung

             dtype messniveau  mittelwert_zulaessig
AAGE         int64      ratio                  True
ACLSWKR        str    nominal                 False
ADTINK       int64    nominal                 False
ADTOCC       int64    nominal                 False
AHGA           str    ordinal                 False
AHSCOL         str    nominal                 False
AMARITL        str    nominal                 False
AMJIND         str    nominal                 False
AMJOCC         str    nominal                 False
ARACE          str    nominal                 False
AREORGN        str    nominal                 False
ASEX           str    nominal                 False
AUNMEM         str    nominal                 False
AUNTYPE        str    nominal                 False
AWKSTAT        str    nominal                 False
CAPGAIN      int64      ratio                  True
GAPLOSS      int64      ratio                  True
DIVVAL       int64      ratio                  True
FILESTAT       str    nominal                 False
GRINREG        str    nominal                 False
GRINST         str    nominal                 False
HHDFMX         str    nominal                 False
HHDREL         str    nominal                 False
MARSUPWRT  float64      ratio                  True
MIGMTR1        str    nominal                 False
MIGMTR3        str    nominal                 False
MIGMTR4        str    nominal                 False
MIGSAME        str    nominal                 False
MIGSUN         str    nominal                 False
NOEMP        int64      ratio                  True
PARENT         str    nominal                 False
PEFNTVTY       str    nominal                 False
PEMNTVTY       str    nominal                 False
PENATVTY       str    nominal                 False
PRCITSHP       str    nominal                 False
SEOTR        int64    nominal                 False
VETQVA         str    nominal                 False
VETYN        int64    nominal                 False
WKSWORK      int64      ratio                  True
AHRSPAY      int64      ratio                  True
year         int64  intervall                  True
income         str    ordinal                 False

Wie unsere Übersicht zeigt, führt der Datentyp `int64` dazu, dass `pandas` mathematisch völlig unzulässige Mittelwerte für rein nominale Variablen (wie z.B. den Berufscode `ADTOCC`) berechnet. Es gibt jedoch auch Spalten wie z.B. `CAPGAIN` (Kapitalgewinne), die den `int64` Datentyp haben, bei denen ein Mittelwert durchaus sinnvoll ist.